server:
  port: 8080

spring:
  application:
    name: job-mvp-api
  data:
    mongodb:
      uri: mongodb+srv://lucianodepaula:1100#MongoDB@mvp.1bxyvyp.mongodb.net/job_mvp_api
      
job_mvp_api:
  app:
    jwtSecret: authenticationSecretKey
    jwtExpirationMs: 86400000